### ISSUE TITLE
It is not staying on top

### ISSUE THREAD

**Issue by jideoyelayo1** [RCCG-JPPD/clock#10]
Need to test with desktop

If your Electron window with `alwaysOnTop: true` is still getting covered by other applications on your desktop environment, there are a few additional steps and considerations you can take to ensure it remains on top effectively:

### 1. Set the Window Type

Electron allows you to specify different types for BrowserWindows. Setting the correct window type can affect how the window behaves in relation to other applications and system UI elements.

```javascript
let privateWindow = new BrowserWindow({
    width: 250,
    height: 100,
    x: 0,
    y: 0,
    frame: false,
    alwaysOnTop: true,
    webPreferences: {
        nodeIntegration: true,
    },
    type: 'desktop' // Set the window type explicitly
});
```

Setting `type: 'desktop'` can help ensure that your window is rendered above most other application windows. This is particularly useful if your Electron application is intended to provide a utility or dashboard that should always be easily accessible.

### 2. Handle Focus Events

In some cases, windows might lose their "always on top" status if they lose focus. You can handle the `focus` event to restore focus to your window if it loses it unexpectedly.

```javascript
privateWindow.on('focus', () => {
    privateWindow.setAlwaysOnTop(true); // Ensure it stays on top when focused
});
```

### 3. Use `setAlwaysOnTop` Dynamically

If your window needs to dynamically adjust its visibility on top of other windows, you can use `setAlwaysOnTop` method based on certain conditions or events in your application.

```javascript
// Example usage to bring the window to the top
function bringWindowToFront() {
    privateWindow.setAlwaysOnTop(true, 'screen-saver');
    setTimeout(() => {
        privateWindow.setAlwaysOnTop(false);
    }, 2000);
}
```

By using these techniques, you can ensure that your Electron application window stays on top as expected, even when other applications are active or in focus on your desktop. This approach should help mitigate issues where your window gets covered unexpectedly.

**Comment by RCCG-JPDAG-TECH-OFFICE** [comment]
workin:
```
const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindows() {
    let privateWindow = new BrowserWindow({
        width: 150,
        height: 50,
        x: 0,
        y: 0,
        frame: false, 
        alwaysOnTop: true,
        webPreferences: {
            nodeIntegration: true,
        },
        type: 'darwin' //'toolbar'
    });

    let publicWindow = new BrowserWindow({
        width: 150,
        height: 50,
        x: 250,
        y: 250,
        frame: false, 
        alwaysOnTop: true,
        webPreferences: {
            nodeIntegration: true,
        },
        type: 'darwin' //'toolbar'
    });

    privateWindow.loadFile(path.join(__dirname, 'private-clock.html'));
    publicWindow.loadFile(path.join(__dirname, 'public-clock.html'));

    const bringToTop = (window) => {
        window.setAlwaysOnTop(true);
        window.showInactive();
    };

    // Ensure the windows stay on top by bringing them to the front periodically
    setInterval(() => {
        bringToTop(privateWindow);
        bringToTop(publicWindow);
    }, 100);
}

app.whenReady().then(createWindows);

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindows();
    }
});

```
